name: CD - Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/final-project || (git clone https://github.com/LuisVelez28/DevOpsFinal.git final-project && cd final-project)

            git pull

            docker login ${{ secrets.NEXUS_DOCKER_REPO_URL }} -u ${{ secrets.NEXUS_USER }} -p ${{ secrets.NEXUS_PASSWORD }}

            docker-compose pull

            docker-compose up -d
