name: CI - Test, Build and Push to Nexus

on:
  push:
    branches:
      - main

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python -m pytest

      - name: Configure Docker for insecure registry
        run: |
          # Crea el archivo de configuración de Docker para permitir la conexión HTTP a tu Nexus
          echo '{"insecure-registries": ["${{ secrets.NEXUS_DOCKER_REPO_URL }}"]}' | sudo tee /etc/docker/daemon.json
          # Reinicia el servicio de Docker para que aplique la nueva configuración
          sudo service docker restart

      - name: Log in to Nexus
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NEXUS_DOCKER_REPO_URL }}
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.NEXUS_DOCKER_REPO_URL }}/fastapi-store-app:latest
            ${{ secrets.NEXUS_DOCKER_REPO_URL }}/fastapi-store-app:${{ github.sha }}